### PR TITLE
use iota_client

### LINKED ISSUE #606: set_client_options says new node is not synced, even if it's synced
## Bug description

set_client_options says new node is not synced, even if it's synced

## Rust version

- Rust version: 1.51.0 (2fd73fabe 2021-03-23)

## Version

- Version number, commit, or branch: b56f5e91b221c91c0883a9e31b4e2722ef8fcf31

## Steps To reproduce the bug

1. Create account
2. set_client_options with another node

## Expected behaviour

Should work if the node is synced

## Actual behaviour

Fails

## Errors

`failed to update client options: NodesNotSynced("https://chrysalis-nodes.iota.org/")`

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

use iota-client because iota-core isn't available anymore

Fixes https://github.com/iotaledger/wallet.rs/issues/606 and https://github.com/iotaledger/wallet.rs/issues/527

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Tests compile

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Thoralf-M** [comment]
@kwek20 can you fix the Java binding? There was an issue with rocksdb, by updating bindgen it's gone, but now it expects struct instead of struct variants

**Comment by Thoralf-M** [comment]
Fixes https://github.com/iotaledger/wallet.rs/issues/606 and https://github.com/iotaledger/wallet.rs/issues/527

**Comment by kwek20** [comment]
on it

**Comment by kwek20** [comment]
@Thoralf-M I updated my other PR, should be good if you merge that first

https://github.com/iotaledger/wallet.rs/pull/597

**Review by rajivshah3 — APPROVED** [review]

**Pull request merged**
