### PR TITLE
Add Java Docs

### PR DESCRIPTION
**Pull request by huhn511**
# Description of change

Add documentation for the Java binding.

## Type of change
- Documentation

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kwek20** [comment]
Just to note; Android example isnt ready for use yet!

**Comment by laumair** [comment]
> Just to note; Android example isnt ready for use yet!

@huhn511 @kwek20 Should this be reflected in the docs?

**Comment by kwek20** [comment]
I would just remove it, and merge this :) iota.rs java bindings already has a more complete docs, that can be used as a reference for an updated version later™

**Comment by Thoralf-M** [comment]
Resolved the conflict in https://github.com/iotaledger/wallet.rs/pull/764 because the branch got deleted

**Pull request closed without merging**
