### PR TITLE
Update workflows to production branch

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Update workflows to production branch

## Links to any relevant issues

Related to https://github.com/iotaledger/wallet.rs/issues/956

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Review by samuel-rufi — DISMISSED** [review]

**Comment by Thoralf-M** [comment]
@Dr-Electron is it normal that the testbuild fails on the production branch? Does the wiki also need an update there?

**Comment by Dr-Electron** [comment]
> @Dr-Electron is it normal that the testbuild fails on the production branch? Does the wiki also need an update there?

What do you mean with it fails? It seems green to me :trollface:

**Comment by Thoralf-M** [comment]
> > @Dr-Electron is it normal that the testbuild fails on the production branch? Does the wiki also need an update there?
> 
> What do you mean with it fails? It seems green to me :trollface:

https://github.com/iotaledger/wallet.rs/runs/6793767298?check_suite_focus=true

**Comment by Dr-Electron** [comment]
> > > @Dr-Electron is it normal that the testbuild fails on the production branch? Does the wiki also need an update there?
> > 
> > 
> > What do you mean with it fails? It seems green to me :trollface:
> 
> https://github.com/iotaledger/wallet.rs/runs/6793767298?check_suite_focus=true

WTF? You can just remove the whole action 😆 
At least the documentation part.

**Review by samuel-rufi — APPROVED** [review]

**Pull request merged**
