### PR TITLE
Remove gh-pages deploy action

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

I removed the GitHub action to stop the documentation deployment as we now have the wiki as single point of knowledge and should keep the old sites running.

Now there are multiple solutions how this could work in the future:
- Merge this PR. PRs for the docs will still be tested by the action
- Remove the complete page. That will also disable the test of PRs
- Add the wiki-cli like identity did. That way you could clean up the documentation folder and use the wiki-cli for testing.
Check their folder content here: https://github.com/iotaledger/identity.rs/tree/dev/documentation

I will keep this PR a draft until you tell me how you want to proceed and I will implement it that way on this PR.

TO-DOs:
- [ ] Decide how to proceed
- [ ] Don't forget to disable GH pages

## Type of change

- Documentation Fix

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jyhi** [comment]
@Thoralf-M what's your idea on it? My opinion is that overtime `gh-pages` adds the size of the repository. It looks like wallet-lib.docs.iota.org now jumps to wiki.iota.org/wallet.rs too. If there are other ways to build and deploy the documentation I'd suggest do it instead of deploying to `gh-pages`.

**Comment by Thoralf-M** [comment]
@Dr-Electron what's the state on this? @lmy441900 we're only waiting to have everything moved to the wiki properly, not sure if that's already the case

**Comment by Dr-Electron** [comment]
I mean everything is already in the wiki. So I would probably remove the GH page action from this repo, add the iota-wiki-cli tool so that you can test your docs in a workflow and we are done ;)

**Comment by jyhi** [comment]
@Dr-Electron As a refurbishment of workflows is currently being undergone, I'll do the job in another PR, so this may be closed :)

You didn't add a workflow for documentation testing, neither do I see the identity.rs repository has it. Is a `yarn` enough to test the build of documentation?

**Comment by Dr-Electron** [comment]
Because no one has it yet 😅
Something needs to be merged in the iota-wiki-cli repo. Don't know if i have the rights to do that. Can check that this weekend i guess

**Comment by Thoralf-M** [comment]
@Dr-Electron can you also remove https://github.com/iotaledger/wallet.rs/blob/dev/documentation/yarn.lock and other things that aren't needed anymore?

**Pull request closed without merging**
