### PR TITLE
Updated API Specification

### PR DESCRIPTION
**Pull request by gtmendler**
# Description of change

Reference ticket: https://github.com/iotaledger/wallet.rs/issues/728

changelog:
- removes storage adapter section
- simplifies tables
- lists most public facing interfaces, functions and parameters
- added new Syncing and Migration sections
future improvements:
- add more detailed descriptions

## Links to any relevant issues

Attempts to fix issue 728 (outdated specification)

## Type of change

- Documentation

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Thoralf-M** [comment]
list_messages() and get_node_info() is missing for the AccountHandle, is there a reason for that?

**Comment by laumair** [comment]
The rendered version has issues. See screenshot.

Screenshot 2021-11-11 at 3 16 26 PM

**Comment by gtmendler** [comment]
sorry yes, it seems some functions were missed due to a mistake in the fingerprint collection due to different formatting. Both mentioned issues should now be resolved

**Review by jyhi — COMMENTED** [review]
The rendered version LGTM, but the HTML tables are not preferable in a Markdown document. I'd suggest changing them to Markdown native notations, but it's also okay to merge this.

**Review by Thoralf-M — APPROVED** [review]

**Pull request merged**
