### PR TITLE
Expose Gap Limit for Customization

### LINKED ISSUE #792: [Feature Request] Increase gap limit when searching for migration data
## Description

As part of legacy to chrysalis migration, we offer an [API](https://github.com/iotaledger/wallet.rs/blob/3a6a9d4c42955e6ecf84d06fffb008bb052861d8/bindings/python/native/src/classes/account_manager.rs#L117-L138) that searches for balance / transaction on a range of addresses starting from an [initialAddressIndex](https://github.com/iotaledger/wallet.rs/blob/bd5240ce0a0c7e8c8d65c3030f83374a3eec651f/src/account_manager/migration.rs#L109) and up to a [gap_limit](https://github.com/iotaledger/wallet.rs/blob/bd5240ce0a0c7e8c8d65c3030f83374a3eec651f/src/account_manager/migration.rs#L108). 

This works well for most of the cases but in some rare cases (where the funds are on a really high index), this proves cumbersome as the user will have to check again & again a lot of times to find the addresses that actually have balance. Imagine a seed having balance on an address with index 500000. 

## Motivation

A client using wallet.rs has the exact same problem as stated above and has requested to provide them a custom version of wallet.rs that has an increased `gap_limit`.

## Requirements

1. Increase the `gap_limit` to 100,000. Test it and analyse if this is a suitable number and doesn't cause any significant delays. If it does, lower the number to such that it is performant enough;
2. Test it with an example directly in wallet.rs and also with [firefly](https://github.com/iotaledger/firefly);

**Important:**

- Rather than using the latest commit, checkout from the commit used by firefly at the time when the latest version of firefly was released. The latest firefly release can be found [here](https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0). Firefly latest release pointed to `firefly-testing` branch of wallet.rs so, would be a good idea to checkout from that branch;
- After the changes, rebuild firefly locally, against the changes and test it. This [blogpost](https://blog.iota.org/firefly-token-migration/) explains how the migration process works in firefly; 
- For testing, the [firefly nodes](https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/migration.ts#L35-L36) can be used;
- Do not create a PR and keep it in a branch.  

## Open questions (optional)

N/A

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by jyhi**
# Description of change

#792 requests a feature for an increased gap limit. It's not wise to hard-code this value, so this PR exposes it, enabling users to customize it according to their needs.

## Links to any relevant issues

Fixes #792.

## Type of change

Enhancement (a non-breaking change which adds functionality).

## How the change has been tested

```
cargo run --example migration
```

It should compile and run.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kwek20** [comment]
I noticed some gap_limit is usize, others u64. We should pick one :)

**Comment by jyhi** [comment]
> some gap_limit is usize, others u64

@kwek20 They should all be u64; which usize are you referring to?

**Comment by kwek20** [comment]
For example `sync_accounts` in `src/actor/mod.rs ` @lmy441900

**Comment by jyhi** [comment]
Oops, indeed. `u64` is from `account_manager/migration.rs`, so there has been this inconsistency before. We should pick one!

**Review by Thoralf-M — APPROVED** [review]
LGTM

**Pull request merged**
