### PR TITLE
update iota.rs to use bee crates from crates.io

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

update iota.rs to use bee crates from crates.io

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Thoralf-M** [comment]
@kwek20 can you fix the Java binding?
There is also `MilestonePayloadRust` and `RustMilestonePayloadEssence`, `Rust` should be used before or afterwards, but not both

**Comment by kwek20** [comment]
Should be done with https://github.com/iotaledger/wallet.rs/pull/583 @Thoralf-M

**Review by lucasfernog — APPROVED** [review]

**Comment by lucasfernog** [comment]
Now we can publish iota.rs right?

**Comment by Thoralf-M** [comment]
@lucasfernog dependencies wise yes

**Pull request merged**
