### PR TITLE
Remove Cargo.lock

### PR DESCRIPTION
**Pull request by jyhi**
# Description of change

Libraries don't have their `Cargo.lock`s checked in: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

This PR removes all `Cargo.lock`s and adds it to `.gitignore`.

## Links to any relevant issues

None.

## Type of change

Enhancement (a non-breaking change ~~which adds functionality~~).

## How the change has been tested

```
cargo test
```

It should pass.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rajivshah3** [comment]
While the Cargo.lock is not checked in for libraries by convention, we include it so that builds are reproducible across CI and development environments. It also helps with caching (https://github.com/iotaledger/wallet.rs/pull/258). @Thoralf-M @laumair what are your thoughts?

**Comment by Thoralf-M** [comment]
For caching it should also work without it I think, but we need to change the workflows so the lock files aren't hashed there and maybe store the target folder after every build (don't know if we have limitations there)

**Comment by jyhi** [comment]
Unless we do have pre-built binary users I would still propose removing it; it's the binary (executable) developers who are responsible for keeping the build reproducible (by including their `Cargo.lock` in their repository).

For workflows I will take some time to look into it to ensure nothing breaks.

**Comment by Thoralf-M** [comment]
> Unless we do have pre-built binary users
For the bindings the binaries are created from our state (for nodejs and python in the workflows), so should we keep them there? For wallet.rs itself I don't see a problem with removing it

**Review by Thoralf-M — APPROVED** [review]

**Comment by rajivshah3** [comment]
We do have people using the prebuilt binaries, so we should at least keep the lockfiles for the bindings.

**Comment by Thoralf-M** [comment]
@rajivshah3 I also thought that, but at the end they will use the released version and there they can just use a fixed version?

**Comment by rajivshah3** [comment]
Hmm, I guess they could. If the prebuilt binary does not work for some reason though, there's no guarantee that they will build their own binary with the same dependencies as the prebuilt one.

**Comment by jyhi** [comment]
I think I need some more investigation. Before this, please don't merge.

**Comment by jyhi** [comment]
I think I closed the PR by accident, but this is what I intend now.

_I did my own research (tm)_ and it turns out to be necessary to keep `Cargo.lock` in the repository and it doesn't actually cause any trouble:

- Our users won't use `Cargo.lock` anyways (neither won't it be published to crates.io).
- We publish binary build ourselves, so `Cargo.lock` is helpful for _our_ deterministic builds.
- "It also helps with caching (#258)" -- in CI workflows; including the hash of `.lock` files in the cache keys looks like a common practice.

Closing this for now (oh it's been closed, nevermind).

**Pull request closed without merging**
